<?php
function gauss_menu() {
    $menu['math'] = array(
        'title' => 'Math Department Admin',
        'page callback' => 'gauss_admin_school',
        'access arguments' => array('access math department administration')
    );

    return $menu;
}

function gauss_admin_school() {
    return '';
}

function gauss_perm() {
    return array('access math department administration');
}

function gauss_user_load($users) {
    foreach (array_keys($users) as $uid) {
        gauss_load_profile($users[$uid]);
    }
}

function gauss_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
    $user = $form['#user'];
    $form_in = gauss_profile_form($form_state, $user);

    $form = array_merge($form, $form_in);
}

function gauss_form_user_register_form_alter(&$form, &$form_state, $form_id) {
    return gauss_form_user_profile_form_alter($form, $form_state, $form_id);
}

function gauss_user_update(&$edit, $account, $category) {
    gauss_profile_save($edit, $account);
}

// function gauss_user($type, &$edit, &$user, $category = NULL) {
//     switch ($type) {
//         case 'submit':
//             $edit['name'] = check_plain($edit['full_name']);
//             break;
//         case 'insert':
//             user_save($user, array('name' => check_plain($edit['full_name']),
//                                    'full_name' => $edit['full_name']));
//             break;
// }

function gauss_user_insert(&$edit, $account, $category) {
    gauss_profile_save($edit, $account);
}

function gauss_user_delete($account) {
    db_query('DELETE FROM {un_user_profile} WHERE uid=?', array($account->uid));
}

function gauss_form_alter(&$form, &$form_state, $form_id) {
    switch ($form_id) {
        case 'user_profile_form':
            $account = $form['#user'];
            // $form['account']['name'] = array('#type' => 'value', '#value' => time());
            $form['account']['full_name'] = array('#type' => 'textfield',
                                                  '#title' => t('Name'),
                                                  '#default_value' => $account->profile ? $account->profile->name : $account->name,
                                                  '#maxlength' => 255,
                                                  '#required' => TRUE,
                                                  '#weight' => -10);
            break;
        case 'user_register_form':
            // $form['account']['name'] = array('#type' => 'value', '#value' => time());
            $form['account']['full_name'] = array('#type' => 'textfield',
                                       '#title' => t('Name'),
                                       '#maxlength' => 255,
                                       '#required' => TRUE,
                                       '#weight' => -10);
            break;
        // case 'user_login':
        //     $form['name']['#title'] = t('E-mail');
        //     $form['name']['#description'] = t('Enter your e-mail address.');
        //     $form['name']['#element_validate'][] = 'gauss_mail_user_login_validate';
        //     break;
        // case 'user_login_block':
        //     $form['name']['#title'] = t('E-mail');
        //     $form['name']['#element_validate'][] = 'gauss_mail_user_login_validate';            
        default:
            break;
    }
}

function gauss_mail_user_login_validate($form, &$form_state) {
    if (isset($form_state['values']['name'])) {
        if ($name = db_result(db_query('SELECT name FROM {users} WHERE LOWER(mail) = LOWER(\'%s\')',
                                       $form_state['values']['name']))) {
            $form_state['values']['name'] = $name;
        }
    }
}

function gauss_profile_save(&$edit, &$user) {
    db_query('DELETE FROM {un_user_profile} WHERE uid = ?', array($user->uid));
    db_query("INSERT INTO {un_user_profile} (uid, name, title, office, extension, interests, bio) VALUES(?, ?, ?, ?, ?, ?, ?)", array($user->uid, $edit['full_name'], $edit['title'], $edit['office'], $edit['extension'], $edit['interests'], $edit['bio']));
    
    $edit['full_name'] = NULL;
    $edit['title'] = NULL;
    $edit['office'] = NULL;
    $edit['extension'] = NULL;
    $edit['interests'] = NULL;
    $edit['bio'] = NULL;
}

function gauss_profile_form(&$edit, &$user) {
    $form = array();
    
    $form['profile'] = array('#type' => 'fieldset',
                             '#title' => t('University Profile'));
    $form['profile']['title'] = array('#type' => 'textfield',
                                      '#title' => t('Title'),
                                      '#default_value' => isset($user->profile) ? $user->profile->title : '',
                                      '#size' => 40,
                                      '#maxlength' => 255);
    $form['profile']['office'] = array('#type' => 'textfield',
                                      '#title' => t('Office'),
                                      '#default_value' => isset($user->profile) ? $user->profile->office : '',
                                      '#size' => 20,
                                      '#maxlength' => 20);
    $form['profile']['extension'] = array('#type' => 'textfield',
                                          '#title' => t('Tel. Extension'),
                                          '#default_value' => isset($user->profile) ? $user->profile->extension : '',
                                          '#size' => 20,
                                          '#maxlength' => 20);                                      
    $form['profile']['interests'] = array('#type' => 'textarea',
                                          '#title' => t('Interests'),
                                          '#default_value' => isset($user->profile) ? $user->profile->interests : '',
                                          '#rows' => 2);                                        
    $form['profile']['bio'] = array('#type' => 'textarea',
                                    '#title' => t('Bio'),
                                    '#default_value' => isset($user->profile) ? $user->profile->bio : '',
                                    '#rows' => 5);
    return $form;
}

function gauss_load_profile(&$user) {
    $res = db_query('SELECT name, title, office, extension, interests, bio FROM {un_user_profile} WHERE uid = ?', array($user->uid));
    $profile = $res->fetchObject();
    $user->profile = $profile ? $profile : NULL;
    
    $user->profile->name = isset($user->profile->name) ? $user->profile->name : $user->name;
}

function gauss_roles($id = NULL) {
    $options = array('administrator' => t('Administrator'),
                     'teacher' => t('Teacher'),
                     'teaching assistant' => t('Teaching assistant'),
                     'staff' => t('Staff'));
    
    if ($id) {
        return $options[$id];
    } else {
        return $options;
    }

}

function gauss_teaching_roles($id = NULL) {
    if ($id)
        return gauss_roles($id);

    return array('teacher' => gauss_roles('teacher'),
                 'teaching assistant' => gauss_roles('teaching assistant'));
}